name: Ruby

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop --parallel --format progress

  rspec:
    runs-on: ubuntu-latest
    needs: ['rubocop']
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', 'head']
    steps:
    - name: Check out branch
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      env:
        RAILS_ENV: test
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run rspec rest of the suite
      run: bundle exec rspec
